### ISSUE TITLE
如何处理证书每3个月更新的问题？

### ISSUE THREAD

**Issue by budui** [FaithPatrick/trojan-caddy-docker-compose#1]
首先很感谢您的项目，非常方便，我很快就搭建完了。但是有个问题，证书每3个月更新一次这个问题是怎么解决的？

**Comment by MortyFx** [comment]
Caddy 容器内置了 acme.sh 脚本，提供证书的自动申请和自动续期。
如果你使用的是它自动生成的证书，就不必关心自动续期的问题。

**Comment by blueveryday** [comment]
自动申请记得是要加tls 邮箱在caddyfile文件里面的，但是这个源码里面没有这个代码？

**Comment by MortyFx** [comment]
> 自动申请记得是要加tls 邮箱在caddyfile文件里面的，但是这个源码里面没有这个代码？

我实测过不需要填写邮箱也能自动完成申请，但现在有个问题，caddy 续签证书后，trojan 要重启才能更新。

**Comment by lmmsoft** [comment]
> > 自动申请记得是要加tls 邮箱在caddyfile文件里面的，但是这个源码里面没有这个代码？
> 
> 我实测过不需要填写邮箱也能自动完成申请，但现在有个问题，caddy 续签证书后，trojan 要重启才能更新。

是的，我也遇到证书续签之后不能使用的情况，重启容器 docker restart trojan-caddy-docker-compose_trojan_1 解决

crontab -e 最后一行添加
`0 0 1 * * docker restart trojan-caddy-docker-compose_trojan_1`
