### ISSUE TITLE
docker-compose up -d之后~

### ISSUE THREAD

**Issue by Lrvineshaw** [FaithPatrick/trojan-caddy-docker-compose#2]
走到"Scanning dependencies of target trojan"这步就卡在11%不动了，换了台VPS还是如此，系统都是ubuntu18.04 LTS

**Comment by MortyFx** [comment]
是 trojan 编译卡住了，可以换个 trojan 版本重新编排一下试试。

方法：
修改`./trojan/Dockerfile`文件，将`ARG VERSION='v1.14.0'`改成`ARG VERSION='v1.15.1'`

如果还是不行的话，可以给 trojan 官方提 issue：https://github.com/trojan-gfw/trojan/issues

**Comment by Lrvineshaw** [comment]
> 是 trojan 编译卡住了，可以换个 trojan 版本重新编排一下试试。
> 
> 方法：
> 修改`./trojan/Dockerfile`文件，将`ARG VERSION='v1.14.0'`改成`ARG VERSION='v1.15.1'`
> 
> 如果还是不行的话，可以给 trojan 官方提 issue：https://github.com/trojan-gfw/trojan/issues

反馈一下，修改以后就通过编译了
