### ISSUE TITLE
请问当前配置是否支持tls1.3？

### ISSUE THREAD

**Issue by MingLocke** [FaithPatrick/trojan-caddy-docker-compose#3]
如果不支持，可以通过修改config文件来支持吗？

**Comment by MortyFx** [comment]
仓库已经更新支持 TLS1.3。

**手工修改方法：**
修改`./trojan/config/config.json` 的第 15 行，将
```"cipher": "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256",```
修改为 ```"cipher_tls13":"TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",```

最后重新启动容器即可。
