### ISSUE TITLE
请问能不能把trojan版本更新到最新版？

### ISSUE THREAD

**Issue by blueveryday** [FaithPatrick/trojan-caddy-docker-compose#5]
现在这个库的版本旧了。
每次要手动修改docker文件。
后来克隆的不方便，谢谢。

另外，运行以后，报错如下：
caddy_1   | 2020/09/05 03:30:59 [INFO] Serving http://xxx.xxx.xxx
caddy_1   | 2020/09/05 03:30:59 [WARNING] Sending telemetry (attempt 1): Post https://telemetry.caddyserver.com/v1/update/bf83e9bc-88b6-4d7f-9a99-ba28c007315a: dial tcp: lookup telemetry.caddyserver.com on 127.0.0.11:53: no such host - backing off and retrying
trojan_1  | Welcome to trojan 1.16.0
trojan_1  | [2020-09-05 03:31:00] [WARN] trojan service (server) started at 0.0.0.0:443
trojan_1  | [2020-09-05 03:31:07] [ERROR] xxxx.xxxx.xxxx.xx:xx SSL handshake failed: sslv3 alert bad certificate
trojan_1  | [2020-09-05 03:31:07] [INFO] xxxx.xxxx.xxxx.xx:xx disconnected, 0 bytes received, 0 bytes sent, lasted for 0 seconds

**Comment by MortyFx** [comment]
已更新 trojan 版本到 v1.16.0.

启动报错是证书错误，有在用 caddy 申请的证书吗？

**Comment by blueveryday** [comment]
> 已更新 trojan 版本到 v1.16.0.
> 
> 启动报错是证书错误，有在用 caddy 申请的证书吗？

https真的需要用tls申请证书，才会后面自动续签。如果需要重启trojan，可能需要在证书续签后，自动重启一次机器了。

**Comment by mutedstack** [comment]
telemetry.caddyserver.com 域名确实找不到，被废弃了：https://caddy.community/t/is-telemetry-caddyserver-com-still-available/7172
因为 abiosoft/caddy 太旧了，改为 caddy。

**Comment by kchen0x** [comment]
全部更新到最新的 镜像，已经发了 PR。
#7
