### ISSUE TITLE
有没有遇到一些速度问题

### ISSUE THREAD

**Issue by soloblack** [FaithPatrick/trojan-caddy-docker-compose#8]
现在运行正常，可以翻，但是速度有问题，同时
github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayPacketLoop.func1.1:proxy.go:141 failed to parse udp packet addr | unable to read ATYP | EOF

有这个错误，我没找到原因

**Comment by MortyFx** [comment]
试试：https://github.com/p4gefau1t/trojan-go/issues/156#issuecomment-674343781

**Comment by soloblack** [comment]
疑似是客户端的问题，已经解决，感谢
